services:
  front:
    container_name: frontend
    image: hamgeonwook/4zopalza_front:latest
    ports:
      - "80:80"
    restart: always

  back:
    container_name: backend
    image: hamgeonwook/4zopalza_back:latest
    ports:
      - "8080:8080"
    restart: always

  data:
    container_name: data
    image: hamgeonwook/4zopalza_data:latest
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always