services:
  front:
    container_name: frontend
    image: hamgeonwook/4zopalza_front:latest
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always

  back:
    container_name: backend
    image: hamgeonwook/4zopalza_back:latest
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always

  data:
    container_name: data
    image: hamgeonwook/4zopalza_data:latest
    environment:
      APP_KEY: ${APP_KEY}
      APP_SECRET: ${APP_SECRET}
      ACC: ${ACC}
      ACC_NO: ${ACC_NO}
      TOKEN: ${TOKEN}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DART_API_KEY: ${DART_API_KEY}
      GPT_API_KEY: ${GPT_API_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
      - mysql
    restart: always
    command: python update.py  # 추가

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
  
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always

volumes:
  mysql-data:
