version: '3'
services:
  front:
    container_name: front  # 컨테이너 이름 설정
    image: hamgeonwook/4zopalza_front:latest
    ports:
      - "80:80"
    restart: always

  back:
    container_name: back  # 컨테이너 이름 설정
    image: hamgeonwook/4zopalza_back:latest
    ports:
      - "8080:8080"
    restart: always

  data:
    container_name: data  # 컨테이너 이름 설정
    image: hamgeonwook/4zopalza_data:latest
    restart: always

  redis:
    container_name: redis  # 컨테이너 이름 설정
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
